export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_ALL_PRODUCTS = 'FETCH_ALL_PRODUCTS';
export const FETCH_ALL_PRODUCTS_CATEGORY = 'FETCH_ALL_PRODUCTS_CATEGORY'
export const LOG_IN_USER = 'LOG_IN_USER';
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const LOG_OUT_USER = 'LOG_OUT_USER';
export const SET_CATEGORY_AND_PRICE = 'SET_CATEGORY_AND_PRICE'
export const FETCH_SINGLE_PRODUCT = 'FETCH_SINGLE_PRODUCT'
export const FETCH_ORDENES = 'FETCH_ORDENES';
export const FETCH_ALL_CATEGORY = 'FETCH_ALL_CATEGORY'
export const FETCH_ALL_LIMIT_CATEGORY = 'FETCH_ALL_LIMIT_CATEGORY'
export const FETCH_CARRITO = 'FETCH_CARRITO';
<<<<<<< HEAD
export const FETCH_ALL_SHOPPING = 'FETCH_ALL_SHOPPING';
=======
export const FETCH_REVIEWS = 'FETCH_REVIEWS'
export const SET_ALERT = 'SET_ALERT';
>>>>>>> def727397cbf337e34f8e1c6d536697f53b6fcc5
